rvm:
  - "2.2.2"
env: 
  - "RAILS_ENV=test CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/features/*_spec.rb"
  - "RAILS_ENV=test CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/models/*_spec.rb"
  - "RAILS_ENV=test CI_CATEGORY=controllers DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/controllers/*_spec.rb"
cache: bundler
sudo: false
addons:
  apt:
    packages:
      - pwgen
      - libicu-dev
services:
  - redis-server
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - mkdir -p public/uploads
  - mkdir -p tmp/cache
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rake rspec-rerun:spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/53f5cd27c87a47426f47
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  code_climate:
    repo_token: e0efa94b3c7a8a2049f5ff1ded51a21e922bf29845e658de598b01c964c17275