# Start with:
# docker-compose up

version: '3'

volumes:
  mysql_data: {}
  redis_data: {}
  neo4j_data: {}
  wingolfsplattform_uploads: {}
  wingolfsplattform_assets: {}

services:
  rails:
    build: .
    depends_on:
      - mysql
      - redis
      - neo4j
    volumes:
      - .:/app/wingolfsplattform
      - ../your_platform:/app/your_platform
      - "wingolfsplattform_uploads:/app/wingolfsplattform/uploads"
      - "wingolfsplattform_assets:/app/wingolfsplattform/public/assets"
      - "./config/secrets.docker.yml:/app/wingolfsplattform/config/secrets.yml"
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      RAILS_ENV: development
      MYSQL_DATABASE: wingolfsplattform_development
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      NEO4J_REST_URL: http://neo4j:trinity@neo4j:7474
    command:
      - ./start

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "wingolfsplattform_development"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "wingolfsplattform"
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - 0.0.0.0:3306:3306

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis

  neo4j:
    image: neo4j:3.5
    volumes:
      - neo4j_data:/data
    ports:
      - "0.0.0.0:7474:7474"
      - "0.0.0.0:7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/trinity"

