ruby_base:
  build: .
  dockerfile: Dockerfile_ruby_base
  volumes:
    - .:/app
  command: bundle exec rails s -p 3000 -b '0.0.0.0'  
  volumes_from:
    - box
  ports:
    - "3000:3000"

web:
  build: .
  dockerfile: Dockerfile_web
  environment:
    - REDIS_HOST=redis
  links:
    - db
    - redis

box:
  image: busybox
  volumes:
    - /box

#nweb_node:
#  build: ./node
#  ports:
#    - "8080:8080"
#  command: rails s -b '0.0.0.0'
#  links:
#    - db
#    - redis

db:
  image: library/mysql:5.6.22
  environment:
    MYSQL_ROOT_PASSWORD: QW124453x # required by mysql image

redis:
  image: redis
  ports:
        - "6379"