# Start with:
# docker-compose --file docker-compose-development.yml up

version: '3'

volumes:
  mysql_data: {}
  redis_data: {}
  neo4j_data: {}

services:
  #wingolfsplattform:
  #  build: .
  #  depends_on:
  #    - wingolfsplattform_mysql
  #    - wingolfsplattform_redis
  #  volumes:
  #    - "wingolfsplattform_uploads:/app/uploads"
  #    - "wingolfsplattform_assets:/app/public/assets"
  #    #- "./services/wingolfsplattform/config/secrets.yml:/app/config/secrets.yml"
  #  ports:
  #    - "0.0.0.0:3001:3000"
  #  environment:
  #    RAILS_ENV: production
  #    MYSQL_DATABASE: wingolfsplattform
  #    MYSQL_USER: wingolfsplattform
  #    MYSQL_PASSWORD: secret
  #    MYSQL_HOST: wingolfsplattform_mysql
  #    REDIS_HOST: wingolfsplattform_redis
  #    NEO4J_REST_URL: wingolfsplattform_neo4j
  #  networks:
  #    - default
  #    - backend
  #  command:
  #    - ./start

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "wingolfsplattform_development"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "wingolfsplattform"
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - 0.0.0.0:3306:3306

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis

  neo4j:
    image: neo4j
    volumes:
      - neo4j_data:/data
    ports:
      - "0.0.0.0:7474:7474"
      - "0.0.0.0:7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/trinity"

