development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  database: wingolfsplattform_development
  pool: 25
  username: root
  password: secret
  host: mysql
  port: 3306

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  database: wingolfsplattform_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: root
  password: secret
  host: mysql
  port: 3306
